In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score	
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

C:\Users\TRIDEV PAL\Downloads\anacondajupiter\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\TRIDEV PAL\Downloads\anacondajupiter\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
print(np.__version__)
print(pd.__version__)

1.26.4
3.0.0

In [3]:
# !pip install --upgrade numpy pandas matplotlibwwwww

In [3]:
df = pd.read_csv(r"C:\Users\TRIDEV PAL\Documents\Capstone project\flipkart_mens_topwear_1000_records.csv")

In [4]:
df.head()

,name,company,price,original_price,discount,offers,size,url,page
0,Men Solid Zip Neck Cotton Blend Black T-Shirt,KAJARU,₹ 298,₹ 999,70% off,Hot Deal,NaN,https://www.flipkart.com/kajaru-solid-men-zip-...,1
1,"Men Printed Polo Neck Cotton Blend Black, Grey...",TRIPR,₹ 338,₹ 999,66% off,"Buy 2 items, save extra 5%",NaN,https://www.flipkart.com/tripr-printed-men-pol...,1
2,Pack of 4 Men Solid Round Neck Cotton Blend Mu...,TRIPR,₹ 459,"₹ 1,999",77% off,"Buy 2 items, save extra 5%",NaN,https://www.flipkart.com/tripr-solid-men-round...,1
3,"Men Striped Zip Neck Cotton Blend Black, White...",Try This,₹ 306,₹ 999,69% off,Only few left,NaN,https://www.flipkart.com/try-striped-men-zip-n...,1
4,Men Solid Henley Neck Cotton Blend Black T-Shirt,TRIPR,₹ 192,"₹ 1,999",90% off,Hot Deal,NaN,https://www.flipkart.com/tripr-solid-men-henle...,1

In [5]:
df.isnull().sum()

name                 0
company              0
price                0
original_price       6
discount             9
offers              49
size              1000
url                  0
page                 0
dtype: int64

In [6]:
df.shape

(1000, 9)

In [7]:
df.columns

Index(['name', 'company', 'price', 'original_price', 'discount', 'offers',
       'size', 'url', 'page'],
      dtype='str')

In [8]:
df.dtypes

name                  str
company               str
price                 str
original_price        str
discount              str
offers                str
size              float64
url                   str
page                int64
dtype: object

In [9]:
df.info

<bound method DataFrame.info of                                                   name      company  price  \
0        Men Solid Zip Neck Cotton Blend Black T-Shirt       KAJARU  ₹ 298
1    Men Printed Polo Neck Cotton Blend Black, Grey...        TRIPR  ₹ 338
2    Pack of 4 Men Solid Round Neck Cotton Blend Mu...        TRIPR  ₹ 459
3    Men Striped Zip Neck Cotton Blend Black, White...     Try This  ₹ 306
4     Men Solid Henley Neck Cotton Blend Black T-Shirt        TRIPR  ₹ 192
..                                                 ...          ...    ...
995      Men Solid Polo Neck Cotton Blend Blue T-Shirt     CANTABIL  ₹ 390
996  Men Striped Round Neck Polyester Grey, White T...        Force  ₹ 243
997  Men Regular Fit Checkered Button Down Collar C...     RED TAPE  ₹ 629
998  Men's Tshirt Men Printed, Typography Round Nec...    BlueFicus  ₹ 325
999   Men Regular Fit Solid Curved Collar Formal Shirt  youth first  ₹ 206

    original_price discount                      offers  size  \
0            ₹ 999  70% off                    Hot Deal   NaN
1            ₹ 999  66% off  Buy 2 items, save extra 5%   NaN
2          ₹ 1,999  77% off  Buy 2 items, save extra 5%   NaN
3            ₹ 999  69% off               Only few left   NaN
4          ₹ 1,999  90% off                    Hot Deal   NaN
..             ...      ...                         ...   ...
995        ₹ 1,299  69% off                    Hot Deal   NaN
996        ₹ 1,999  87% off                    Hot Deal   NaN
997        ₹ 3,499  82% off                    Hot Deal   NaN
998          ₹ 999  67% off                    Hot Deal   NaN
999          ₹ 899  77% off                    Hot Deal   NaN

                                                   url  page
0    https://www.flipkart.com/kajaru-solid-men-zip-...     1
1    https://www.flipkart.com/tripr-printed-men-pol...     1
2    https://www.flipkart.com/tripr-solid-men-round...     1
3    https://www.flipkart.com/try-striped-men-zip-n...     1
4    https://www.flipkart.com/tripr-solid-men-henle...     1
..                                                 ...   ...
995  https://www.flipkart.com/cantabil-solid-men-po...    25
996  https://www.flipkart.com/force-striped-men-rou...    25
997  https://www.flipkart.com/red-tape-men-checkere...    25
998  https://www.flipkart.com/blueficus-printed-typ...    25
999  https://www.flipkart.com/youth-first-men-solid...    25

[1000 rows x 9 columns]>

In [10]:
df.describe()

       size         page
count   0.0  1000.000000
mean    NaN    13.000000
std     NaN     7.214711
min     NaN     1.000000
25%     NaN     7.000000
50%     NaN    13.000000
75%     NaN    19.000000
max     NaN    25.000000

## PHASE 2 : DATA CLEANING & PREPROCESSING

In [11]:
df.columns

Index(['name', 'company', 'price', 'original_price', 'discount', 'offers',
       'size', 'url', 'page'],
      dtype='str')

In [12]:
df['price'] = (
    df['price']
    .str.replace(r'[^\d.]', '', regex=True)
    .astype(float)
)

In [13]:
df['original_price'] = (
    df['original_price']
    .str.replace(r'[^\d.]', '', regex=True)
    .astype(float)
)

In [14]:
df['original_price'] = pd.to_numeric(
    df['original_price'].astype(str).str.replace(r'[^\d.]', '', regex=True),
    errors='coerce'
)

In [15]:
df['discount'] = (
    df['discount']
    .str.extract(r'(\d+)')
    .astype(float)
)

In [16]:
df.head()

,name,company,price,original_price,discount,offers,size,url,page
0,Men Solid Zip Neck Cotton Blend Black T-Shirt,KAJARU,298.0,999.0,70.0,Hot Deal,NaN,https://www.flipkart.com/kajaru-solid-men-zip-...,1
1,"Men Printed Polo Neck Cotton Blend Black, Grey...",TRIPR,338.0,999.0,66.0,"Buy 2 items, save extra 5%",NaN,https://www.flipkart.com/tripr-printed-men-pol...,1
2,Pack of 4 Men Solid Round Neck Cotton Blend Mu...,TRIPR,459.0,1999.0,77.0,"Buy 2 items, save extra 5%",NaN,https://www.flipkart.com/tripr-solid-men-round...,1
3,"Men Striped Zip Neck Cotton Blend Black, White...",Try This,306.0,999.0,69.0,Only few left,NaN,https://www.flipkart.com/try-striped-men-zip-n...,1
4,Men Solid Henley Neck Cotton Blend Black T-Shirt,TRIPR,192.0,1999.0,90.0,Hot Deal,NaN,https://www.flipkart.com/tripr-solid-men-henle...,1

In [17]:
df.isnull().sum()

name                 0
company              0
price                0
original_price       6
discount             9
offers              49
size              1000
url                  0
page                 0
dtype: int64

In [18]:
df['original_price'] = df['original_price'].fillna(df['original_price'].median())

In [19]:
df['discount'] = df['discount'].fillna(0)

In [20]:
df['offers'] = df['offers'].fillna("No Offer")

In [21]:
df.isnull().sum()

name                 0
company              0
price                0
original_price       0
discount             0
offers               0
size              1000
url                  0
page                 0
dtype: int64

In [23]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            1000 non-null   str
 1   company         1000 non-null   str
 2   price           1000 non-null   float64
 3   original_price  1000 non-null   float64
 4   discount        1000 non-null   float64
 5   offers          1000 non-null   str
 6   size            0 non-null      float64
 7   url             1000 non-null   str
 8   page            1000 non-null   int64
dtypes: float64(4), int64(1), str(4)
memory usage: 485.2 KB

,name,company,price,original_price,discount,offers,size,url,page
0,Men Solid Zip Neck Cotton Blend Black T-Shirt,KAJARU,298.0,999.0,70.0,Hot Deal,NaN,https://www.flipkart.com/kajaru-solid-men-zip-...,1
1,"Men Printed Polo Neck Cotton Blend Black, Grey...",TRIPR,338.0,999.0,66.0,"Buy 2 items, save extra 5%",NaN,https://www.flipkart.com/tripr-printed-men-pol...,1
2,Pack of 4 Men Solid Round Neck Cotton Blend Mu...,TRIPR,459.0,1999.0,77.0,"Buy 2 items, save extra 5%",NaN,https://www.flipkart.com/tripr-solid-men-round...,1
3,"Men Striped Zip Neck Cotton Blend Black, White...",Try This,306.0,999.0,69.0,Only few left,NaN,https://www.flipkart.com/try-striped-men-zip-n...,1
4,Men Solid Henley Neck Cotton Blend Black T-Shirt,TRIPR,192.0,1999.0,90.0,Hot Deal,NaN,https://www.flipkart.com/tripr-solid-men-henle...,1

### • Create useful features (rating %, price band, category, etc.)

In [24]:
df['discount_pct'] = ((df['original_price'] - df['price']) / df['original_price']) * 100
df['discount_pct'] = df['discount_pct'].round(2)

In [25]:
df.discount_pct

0      70.17
1      66.17
2      77.04
3      69.37
4      90.40
       ...
995    69.98
996    87.84
997    82.02
998    67.47
999    77.09
Name: discount_pct, Length: 1000, dtype: float64

In [26]:
df['savings'] = df['original_price'] - df['price']
df.savings

0       701.0
1       661.0
2      1540.0
3       693.0
4      1807.0
        ...
995     909.0
996    1756.0
997    2870.0
998     674.0
999     693.0
Name: savings, Length: 1000, dtype: float64

In [27]:
def price_band(p):
    if p < 500:
        return "Budget"
    elif 1500 <= p:
        return "Mid-Range"
    else:
        return "Premium"

df['price_band'] = df['price'].apply(price_band)
df.price_band

0       Budget
1       Budget
2       Budget
3       Budget
4       Budget
        ...
995     Budget
996     Budget
997    Premium
998     Budget
999     Budget
Name: price_band, Length: 1000, dtype: str

In [28]:
df.price_band.unique()

<ArrowStringArray>
['Budget', 'Premium']
Length: 2, dtype: str

In [29]:
df[df['price_band']=='Mid-Range']

Empty DataFrame
Columns: [name, company, price, original_price, discount, offers, size, url, page, discount_pct, savings, price_band]
Index: []

In [30]:
df['high_discount'] = df['discount_pct'].apply(lambda x: 1 if x >= 50 else 0)
df.high_discount

0      1
1      1
2      1
3      1
4      1
      ..
995    1
996    1
997    1
998    1
999    1
Name: high_discount, Length: 1000, dtype: int64

In [31]:
df.high_discount.unique()

array([1, 0], dtype=int64)

In [32]:
df[df['high_discount']== 0]

,name,company,price,original_price,discount,offers,size,url,page,discount_pct,savings,price_band,high_discount
25,Men Solid Round Neck Polyester Dark Blue T-Shirt,JOCKEY,998.0,999.0,0.0,Only few left,NaN,https://www.flipkart.com/jockey-solid-men-roun...,1,0.10,1.0,Premium,0
155,Men Solid Round Neck Polyester Dark Blue T-Shirt,JOCKEY,998.0,999.0,0.0,Only few left,NaN,https://www.flipkart.com/jockey-solid-men-roun...,4,0.10,1.0,Premium,0
173,Pack of 1 Pace Intellieaze Men Solid Crew Neck...,XYXX,399.0,469.0,14.0,Only few left,NaN,https://www.flipkart.com/xyxx-solid-men-crew-n...,5,14.93,70.0,Budget,0
258,Men Solid Polo Neck Pure Cotton White T-Shirt,LOUIS PHILIPPE,884.0,1499.0,41.0,Hot Deal,NaN,https://www.flipkart.com/louis-philippe-solid-...,7,41.03,615.0,Premium,0
303,Pack of 1 Pace Intellieaze Men Solid Crew Neck...,XYXX,399.0,449.0,11.0,No Offer,NaN,https://www.flipkart.com/xyxx-solid-men-crew-n...,8,11.14,50.0,Budget,0
453,Men Solid Polo Neck Polyester Grey T-Shirt,Maxzone,402.0,579.0,30.0,Hot Deal,NaN,https://www.flipkart.com/maxzone-solid-men-pol...,12,30.57,177.0,Budget,0
463,Men Slim Fit Checkered Formal Shirt,PARK AVENUE,883.0,1699.0,48.0,Hot Deal,NaN,https://www.flipkart.com/park-avenue-men-check...,12,48.03,816.0,Premium,0
485,Men Solid Zip Neck Polyester Green T-Shirt,TECHNOSPORT,478.0,559.0,14.0,No Offer,NaN,https://www.flipkart.com/technosport-solid-men...,13,14.49,81.0,Budget,0
535,Men Tailored Fit Solid Cut Away Collar Casual ...,U.S. POLO ASSN.,1139.0,1999.0,43.0,Hot Deal,NaN,https://www.flipkart.com/u-s-polo-assn-men-sol...,14,43.02,860.0,Premium,0
555,Men Solid Polo Neck Cotton Blend Blue T-Shirt,DUKE,649.0,999.0,35.0,No Offer,NaN,https://www.flipkart.com/duke-solid-men-polo-n...,14,35.04,350.0,Premium,0
558,Men Solid Zip Neck Polyester Red T-Shirt,TECHNOSPORT,478.0,559.0,14.0,No Offer,NaN,https://www.flipkart.com/technosport-solid-men...,14,14.49,81.0,Budget,0
569,Men Regular Fit Self Design Formal Shirt,Raymond,1310.0,2299.0,43.0,Hot Deal,NaN,https://www.flipkart.com/raymond-men-self-desi...,15,43.02,989.0,Premium,0
625,Men Solid Polo Neck Polycotton Green T-Shirt,PETER ENGLAND,648.0,1099.0,41.0,Hot Deal,NaN,https://www.flipkart.com/peter-england-solid-m...,16,41.04,451.0,Premium,0
632,AM38 Men Solid Polo Neck Polyester Black T-Shirt,JOCKEY,1019.0,1499.0,0.0,No Offer,NaN,https://www.flipkart.com/jockey-solid-men-polo...,16,32.02,480.0,Premium,0
683,AM38 Men Solid Polo Neck Polyester Black T-Shirt,JOCKEY,1019.0,1499.0,0.0,No Offer,NaN,https://www.flipkart.com/jockey-solid-men-polo...,18,32.02,480.0,Premium,0
712,Pack of 1 Pace Intellieaze Men Solid Crew Neck...,XYXX,399.0,469.0,14.0,No Offer,NaN,https://www.flipkart.com/xyxx-solid-men-crew-n...,18,14.93,70.0,Budget,0
802,Men Solid Polo Neck Pure Cotton Purple T-Shirt,LOUIS PHILIPPE,884.0,1499.0,41.0,Hot Deal,NaN,https://www.flipkart.com/louis-philippe-solid-...,21,41.03,615.0,Premium,0
882,Men Solid Polo Neck Polycotton Green T-Shirt,PETER ENGLAND,604.0,1099.0,45.0,Hot Deal,NaN,https://www.flipkart.com/peter-england-solid-m...,23,45.04,495.0,Premium,0
888,Men Solid Polo Neck Pure Cotton Black T-Shirt,Snitch,1398.0,1399.0,0.0,No Offer,NaN,https://www.flipkart.com/snitch-solid-men-polo...,23,0.07,1.0,Premium,0
992,Men Solid Polo Neck Pure Cotton Blue T-Shirt,Lux Nitro,291.0,351.0,17.0,Hot Deal,NaN,https://www.flipkart.com/lux-nitro-solid-men-p...,25,17.09,60.0,Budget,0

In [33]:
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            1000 non-null   str
 1   company         1000 non-null   str
 2   price           1000 non-null   float64
 3   original_price  1000 non-null   float64
 4   discount        1000 non-null   float64
 5   offers          1000 non-null   str
 6   size            0 non-null      float64
 7   url             1000 non-null   str
 8   page            1000 non-null   int64
 9   discount_pct    1000 non-null   float64
 10  savings         1000 non-null   float64
 11  price_band      1000 non-null   str
 12  high_discount   1000 non-null   int64
dtypes: float64(6), int64(2), str(5)
memory usage: 522.4 KB

In [34]:
df.drop(columns=['size'], inplace=True)

In [35]:
df.columns

Index(['name', 'company', 'price', 'original_price', 'discount', 'offers',
       'url', 'page', 'discount_pct', 'savings', 'price_band',
       'high_discount'],
      dtype='str')

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            1000 non-null   str
 1   company         1000 non-null   str
 2   price           1000 non-null   float64
 3   original_price  1000 non-null   float64
 4   discount        1000 non-null   float64
 5   offers          1000 non-null   str
 6   url             1000 non-null   str
 7   page            1000 non-null   int64
 8   discount_pct    1000 non-null   float64
 9   savings         1000 non-null   float64
 10  price_band      1000 non-null   str
 11  high_discount   1000 non-null   int64
dtypes: float64(5), int64(2), str(5)
memory usage: 514.6 KB